version: '3.4'

services:
  order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  product:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

